# spring.h2.console.enabled=true
# spring.datasource.url=jdbc:h2:mem:bookdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
spring.application.name=book-tracker

spring.datasource.url=jdbc:postgresql://booktracker-postgres.postgres.database.azure.com:5432/booktracker?sslmode=require
spring.datasource.username=postgresadmin
spring.datasource.password=Mr.P0P0seulgi

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate    
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

application.jwt.secret-key=book-tracker-secret-key-book-tracker-secret-key-2026
application.jwt.token-prefix=Bearer
application.jwt.token-expiration=1
application.jwt.refresh-token-expiration=7