spring.application.name=book-tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/booktrackerdb
spring.datasource.username=postgres
spring.datasource.password=mac

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
application.jwt.secret-key=book-tracker-secret-key-book-tracker-secret-key-2026
application.jwt.token-prefix=Bearer
application.jwt.token-expiration=1
application.jwt.refresh-token-expiration=7